apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data-pvc
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-addons-pvc
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
