apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: odoo-prod-probe
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - http://odoo-prod.odoo-prod.svc.cluster.local:8069/web/health
        - http://odoo-prod.odoo-prod.svc.cluster.local:8069/web/database/selector