apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-staging-data-pvc
  namespace: odoo-staging
  labels:
    app: odoo-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-staging-addons-pvc
  namespace: odoo-staging
  labels:
    app: odoo-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi
