apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: odoo-prod-probe
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://odoo-prod.odoo-prod.svc.cluster.local:8069/web/health
      labels:
        app: odoo-prod
        namespace: odoo-prod