apiVersion: v1
kind: Secret
metadata:
  name: odoo-staging-secrets
  namespace: odoo-staging
  labels:
    app: odoo-staging
type: Opaque
data:
  ODOO_ADMIN_PASSWORD: MjE0T2Rvbw==
  DB_PASSWORD: b2Rvbw==
