apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-prod-data-pvc
  namespace: odoo-prod
  labels:
    app: odoo-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-prod-addons-pvc
  namespace: odoo-prod
  labels:
    app: odoo-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi
